### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by loopbackseal** [Rob-Yoo/ApusCheckIn_Team1#4]
### 앞으로 진행 예정

- [x] meter 단위를 km로 변환, 0km인 경우 My Distance From ... 대신 CheckIn Available 표시!
- [ ] IDFV가 firestore에 등록되지 않은 경우, pop-up을 띄워 IntraID를 받도록 하고, 그 내용을 firestore에 저장
- [ ] 네비게이션 뷰를 통해 버튼 클릭시 다음 화면(캘린더)로 넘어가도록 하기
